### ISSUE TITLE
Can add account signers but can't delete them

### ISSUE THREAD

**Issue by sacarlson** [astroband/ruby-stellar-base#16]
Seems I can add account signers with no problem but just can't delete them when I set weight to zero they are still listed on the stellar-core db with a weight of 1.  the function I run that works to add but fails to delete with weight set to 0 is:

def add_signer_public_key(account, key, weight)
  set_options account, signer: Stellar::Signer.new({
    pub_key: key,
    weight: weight
  })
end

but I also tried to delete a signer from the developer web interface https://www.stellar.org/developers/tools/client/#/accountmanager and find I can't delete it from there also but have no problem adding them there.  so maybe the problem is at the stellar-core level or something else?
account I was using:

  "address": "GDBGEVX7CD5AS3ECPPJMDUGXK25DFUM5JK5DHDSMNYND46SPC2OMDJZY",
  "secret": "SBPXGA7EEX3Y6LSNNZW3OBXI5UBV2PLH65PTBNNOWCIVDJVSHUSBNJGS"
}

**Comment by nullstyle** [comment]
Closing this in favor of https://github.com/stellar/stellar-core/issues/755
