### ISSUE TITLE
account signature present checked before needed in transaction creation

### ISSUE THREAD

**Issue by sacarlson** [astroband/ruby-stellar-base#17]
I'm getting this error:
stellar-base-0.6.1/lib/stellar/transaction.rb:97:in `for_account': Bad :account (ArgumentError)
this is coming from this line:
raise ArgumentError, "Bad :account" unless account.is_a?(KeyPair) && account.sign?
I'm not totaly sure I'm right about this but why do I need to have an account with a signature at this stage?
shouldn't this line be just:
raise ArgumentError, "Bad :account" unless account.is_a?(KeyPair)
there is no need for any signatures in the structure of a tx as far as I know.  the signature seed should only be needed later to be present at the envelope creation event time.
I am presently creating transactions that are not yet going to be signed by the final sender of the transaction but I am adding a signature of one of the signers.  the transaction will be later sent with the added signature of the target_account added to the envelope at a later time.
this check makes this not posible
sacarlson 5:38 PM with this change implemented in test, my transactions can now be created.   I still see I will get errors at the stage of to_envelope stage so it looks like this works ok so far.  I'll try it for a bit to make sure what other problems it might bring.

**Comment by nullstyle** [comment]
Yeah, the account provided doesn't need to be able to sign transactions... it's a bug.  I'll get it fixed when I get some time to work on the library, but would be happy to take a PR.

**Comment by sacarlson** [comment]
cool my first PR merged.  so do I close this?
